FROM golang:1.25.5-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o jrpc-server ./cmd/gateway

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/jrpc-server .
EXPOSE 8080
CMD ["./jrpc-server"]
